---
- name: Create the deploy user
  user:
    name: deploy
    shell: /bin/bash
    password: "*"
  become: true

- name: Allow 'deploy' to have passwordless sudo star
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: ' start grapevine'
    line: 'deploy ALL=(ALL) NOPASSWD: /bin/systemctl start grapevine'
    validate: 'visudo -cf %s'
  become: true

- name: Allow 'deploy' to have passwordless sudo stop
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: ' stop grapevine'
    line: 'deploy ALL=(ALL) NOPASSWD: /bin/systemctl stop grapevine'
    validate: 'visudo -cf %s'
  become: true

- name: Allow 'deploy' to have passwordless sudo restart
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: ' restart grapevine'
    line: 'deploy ALL=(ALL) NOPASSWD: /bin/systemctl restart grapevine'
    validate: 'visudo -cf %s'
  become: true

- name: Forward SSH socket through sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: 'Defaults    env_keep+=SSH_AUTH_SOCK'
    validate: 'visudo -cf %s'
  become: true
